"""empty message

Revision ID: 9cb1eada276a
Revises: 85cb224996d7
Create Date: 2021-05-24 11:14:37.243230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb1eada276a'
down_revision = '85cb224996d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('mrname', sa.String(length=150), nullable=False),
    sa.Column('votecount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mrname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
