"""empty message

Revision ID: cd1933703a3d
Revises: 
Create Date: 2021-05-04 17:16:12.672992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1933703a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('user_pw', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=False),
    sa.Column('user_add', sa.Text(), nullable=False),
    sa.Column('user_sex', sa.Text(), nullable=False),
    sa.Column('user_sch', sa.Text(), nullable=False),
    sa.Column('user_hby', sa.Text(), nullable=False),
    sa.Column('user_date', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('userinfo')
    op.drop_table('question')
    # ### end Alembic commands ###
